# File: .github/workflows/workflowForFile.yml

on: [push]

name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            New-AzResourceGroupDeployment -Name "EPISODE3"  --ResourceGroupName "DAASNXTRG-US-EAST" --TemplateFile storage.json --TemplateParameterFile storage.parameters.json
